#!/usr/bin/env python
import re
from pathlib import Path
from argparse import ArgumentParser


def main():
  arg_parser = ArgumentParser(
      description='Put <!-- nav --><!-- /nav --> in file.')
  arg_parser.add_argument('file', help='Markdown File', nargs='+')
  arg_parser.add_argument(
      '--title', default='Table of Contents', help='Nav Title')
  args = arg_parser.parse_args()

  for file in args.file:
    with Path(file).resolve().open('r+') as fp:
      contents = fp.read()
      # Сначала нормализуем контент, удаляя все вставки кода
      contents2 = re.sub(r'`.*?`', '', contents, flags=re.S)

      contents2 = re.sub(r'\<!-- (nav) --\>.*?\<!-- /\1 --\>',
                         '', contents2, flags=re.S)

      # Теперь ищем заголовки
      headers = re.findall('^#.*', contents2, re.M)

      nav = ['', f'# {args.title}', '']
      for header in headers:
        name = header.lstrip('#')
        depth = len(header) - len(name)
        name = name.strip()
        # Теперь вырезаем ссылки
        name = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', name)
        uri = name.lower()
        # Вырезаем все не буквенно-цифровые символы
        # «-» то же не нужно вырезать
        uri = re.sub(r'[^\w\s-]', '', uri)
        # Заменяем пробелы на «-»
        uri = uri.replace(' ', '-')
        nav.append('   ' * (depth - 1) + f'1. [{name}](#{uri})')

      nav.append('')
      contents = re.sub(r'(?<=\<!-- (nav) --\>).*?(?=\<!-- /\1 --\>)',
                        '\n'.join(nav), contents, flags=re.S)

      fp.seek(0)
      fp.truncate()
      fp.write(contents)


if __name__ == '__main__':
  main()
